services:
  db:
    image: postgres:15-alpine
    container_name: rails_postgres
    restart: on-failure
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: rails_organizational-chart
    restart: on-failure
    env_file: .env
    command: [
      "bash", "-c", 
      "bin/rails db:create && \
      bin/rails db:migrate && \
      bin/rails db:seed && \
      bin/rails s -p 3000 -b '0.0.0.0'"
    ]
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      SECRET_KEY_BASE : ${RAILS_SECRET_KEY_BASE}

volumes:
  postgres_data:
    driver: local
