default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USER") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  host: <%= ENV.fetch("DB_HOST") %>


development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") %>_development

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") %>_test

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("DB_NAME") %>_production
  cache:
    <<: *primary_production
    database: <%= ENV.fetch("DB_NAME") %>_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV.fetch("DB_NAME") %>_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV.fetch("DB_NAME") %>_production_cable
    migrations_paths: db/cable_migrate
